//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularApp.API.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonalLoanQuote
    {
        public System.Guid QuoteReference { get; set; }
        public int TermInMonths { get; set; }
        public double LoanAmount { get; set; }
        public double Deposit { get; set; }
    
        public virtual Quote Quote { get; set; }
    }
}
