//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularApp.API.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteDefault
    {
        public int TypeID { get; set; }
        public string ElementDescription { get; set; }
        public string XMLTemplate { get; set; }
        public bool Enabled { get; set; }
        public string TotalRepayableTemplate { get; set; }
        public string MonthlyRepayableTemplate { get; set; }
    
        public virtual QuoteType QuoteType { get; set; }
    }
}
