//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularApp.API.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public System.Guid QuoteReference { get; set; }
        public int QuoteType { get; set; }
        public int QuoteStatus { get; set; }
        public int ProductType { get; set; }
        public System.DateTime QuoteDate { get; set; }
        public string QuoteAuthor { get; set; }
    
        public virtual PersonalLoanQuote PersonalLoanQuote { get; set; }
        public virtual PersonalLoanResult PersonalLoanResult { get; set; }
        public virtual ProductType NaviProductType { get; set; }
        public virtual QuoteStatus NaviQuoteStatus { get; set; }
        public virtual QuoteType NaviQuoteType { get; set; }
    }
}
