//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AngularApp.API.Models.DBModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteType
    {
        public int TypeID { get; set; }
        public string ACQuoteType { get; set; }
        public int ProductParentID { get; set; }
        public bool Enabled { get; set; }
    }
}
